package com.google.android.apps.gsa.nga.shared.u.d.a;

import com.google.protobuf.bo;

/* loaded from: classes-dex2jar.jar:com/google/android/apps/gsa/nga/shared/u/d/a/j.class */
public enum j implements bo {
    FAILURE_CAUSE_UNKNOWN(0),
    SEARCH_SERVICE_CALL_FAILED(1),
    EXECUTION_MISMATCH(2),
    STATE_CHANGE_IDLE(3),
    TIMEOUT(4),
    GESTURE_NOT_SWIPE(5),
    PIE_NOT_ELIGIBLE(6),
    SWIPE_INVOCATION_DISMISSED(7),
    LIGHTWEIGHT_SWIPE_INVOCATION_DISMISSED(29),
    LIGHTWEIGHT_LONG_PRESS_HOME_INVOCATION_DISMISSED(41),
    UI_EXIT_CLICKED(20),
    PRECONDITIONS_FAILED(8),
    FLOW_ALREADY_IN_PROGRESS(9),
    FLOW_STATES_EMPTY(10),
    TRIGGER_PIE_NOT_ELIGIBLE(11),
    TRIGGER_FLOW_IN_PROGRESS(12),
    TRIGGER_FLOW_CREATION_FAILED(13),
    TRIGGER_SCREEN_LOCKED(21),
    TRIGGER_NOTIFICATION_DISMISSED(14),
    TRIGGER_NOTIFICATION_ALREADY_ACTIVE(15),
    TRIGGER_NOTIFICATION_ALREADY_DISPLAYED(16),
    TRIGGER_NOTIFICATION_DISPLAY_FAILED(17),
    TRIGGER_NOTIFICATION_GLOBAL_CAP_REACHED(18),
    TRIGGER_NOTIFICATION_INVALID_DATA(19),
    TRIGGER_NOTIFICATION_FAILED_TO_CREATE_PENDINGINTENT(22),
    TRIGGER_NOTIFICATION_RATE_LIMITED_GLOBALLY(23),
    TRIGGER_NOTIFICATION_RATE_LIMITED_PER_FLOW(24),
    TRIGGER_NOTIFICATION_RATE_LIMITED_PER_FLOW_SUCCESS(31),
    TRIGGER_NOTIFICATION_MAXIMUM_PER_FLOW(32),
    TRIGGER_NOTIFICATION_PIE_NOT_ENABLED(25),
    TRIGGER_NOTIFICATION_PIE_NOT_ELIGIBLE(26),
    TRIGGER_NOTIFICATION_USER_IS_COUNTERFACTUAL(33),
    TRIGGER_NOTIFICATION_INIT_DELAY(45),
    TRIGGER_SWIPE_EDUCATION_USER_IS_NOT_ASSISTANT_USER(27),
    TRIGGER_SWIPE_EDUCATION_USER_IS_SWIPE_USER(28),
    TRIGGER_ONDEVICE_ACTION_LOGGING_NOT_ENABLED(30),
    NGA_OPA_PROMO_NOTIFICATION_FLOW_NOT_SPECIFIED(34),
    LISTENING_TIMEOUT(35),
    LISTENING_CANCELLATION(36),
    LISTENING_IMPLICIT_DISMISSAL(37),
    ASSISTANT_TRIGGER_NOT_AVAILABLE(38),
    HOTWORD_INVOCATION_TRYSAYING_DISMISSED(39),
    TRIGGER_OPEN_APP_HOTWORD_NOT_ENABLED(40),
    TRIGGER_UI_NOT_SUPPORTED(42),
    TRIGGER_OPA_PROACTIVE_NOTIFICATION_FAILED(43),
    TRIGGER_OPA_PROACTIVE_NOTIFICATION_TAP_FAILED(44),
    WAIT_FOR_FOREGROUND_APP_ERROR(46),
    WAIT_FOR_FOREGROUND_APP_NEGATIVE(47),
    TRIGGER_INVALID_REQUEST(48),
    NOTIFICATIONS_DISABLED(49);

    public final int Y;

    j(int i) {
        this.Y = i;
    }

    public final int getNumber() {
        return this.Y;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.Y);
    }
}
