package com.google.android.apps.gsa.nga.engine.ui.e.h.a.a;

import android.content.Context;
import com.google.android.apps.gsa.nga.engine.ak.v.a.e;
import com.google.android.apps.gsa.nga.engine.am.g;
import com.google.android.apps.gsa.nga.engine.education.w;
import com.google.android.apps.gsa.nga.engine.n.e.ac;
import com.google.android.apps.gsa.nga.engine.ui.e.d.b;
import com.google.android.apps.gsa.nga.engine.ui.e.h.s;
import com.google.android.apps.gsa.nga.engine.v.a.j;
import com.google.android.apps.gsa.nga.shared.aj.a.c;
import com.google.android.apps.gsa.nga.shared.f.a.ag;
import com.google.android.apps.gsa.nga.shared.f.a.ap;
import com.google.android.apps.gsa.nga.shared.f.a.t;
import com.google.android.apps.gsa.nga.shared.q.a.x;
import com.google.android.apps.gsa.nga.shared.ui.assistlayer.e.l;
import com.google.android.apps.search.assistant.surfaces.voice.m.b.a.c.i;
import com.google.android.libraries.gsa.h.h;
import com.google.android.libraries.search.account.y;
import com.google.common.base.ci;
import com.google.common.v.f;
import e.c.d;
import java.util.Set;

/* loaded from: classes-dex2jar.jar:com/google/android/apps/gsa/nga/engine/ui/e/h/a/a/a.class */
public final class a implements d {
    public static b b(com.google.android.apps.gsa.nga.engine.ui.e.h.a.b bVar) {
        com.google.android.apps.gsa.nga.engine.ui.e.h.a.a aVar = new com.google.android.apps.gsa.nga.engine.ui.e.h.a.a(bVar);
        ci ciVar = bVar.f740a;
        ciVar.getClass();
        f fVar = bVar.b;
        fVar.getClass();
        h hVar = bVar.c;
        hVar.getClass();
        h hVar2 = bVar.d;
        hVar2.getClass();
        h hVar3 = bVar.e;
        hVar3.getClass();
        h hVar4 = bVar.f;
        hVar4.getClass();
        Context context = bVar.g;
        context.getClass();
        Context context2 = bVar.h;
        context2.getClass();
        com.google.android.apps.gsa.shared.logger.b.h hVar5 = bVar.i;
        hVar5.getClass();
        com.google.android.apps.gsa.shared.util.q.a aVar2 = bVar.j;
        aVar2.getClass();
        y yVar = bVar.E;
        yVar.getClass();
        bVar.X.getClass();
        com.google.android.apps.gsa.shared.o.a.a aVar3 = bVar.k;
        aVar3.getClass();
        ag agVar = bVar.F;
        agVar.getClass();
        c cVar = bVar.G;
        cVar.getClass();
        ap apVar = bVar.Y;
        apVar.getClass();
        t tVar = bVar.H;
        tVar.getClass();
        com.google.android.apps.gsa.nga.shared.p.b bVar2 = bVar.l;
        bVar2.getClass();
        x xVar = bVar.I;
        xVar.getClass();
        l lVar = bVar.m;
        lVar.getClass();
        com.google.android.apps.gsa.nga.engine.am.a.a aVar4 = bVar.n;
        aVar4.getClass();
        g gVar = bVar.o;
        gVar.getClass();
        w wVar = bVar.p;
        wVar.getClass();
        Set set = bVar.q;
        set.getClass();
        com.google.android.apps.gsa.nga.engine.am.f fVar2 = bVar.z;
        fVar2.getClass();
        e eVar = bVar.R;
        eVar.getClass();
        com.google.android.apps.gsa.nga.engine.aa.c cVar2 = bVar.J;
        cVar2.getClass();
        com.google.android.apps.gsa.nga.engine.ac.a.ag agVar2 = bVar.K;
        agVar2.getClass();
        bVar.S.getClass();
        j jVar = bVar.T;
        jVar.getClass();
        com.google.android.apps.gsa.nga.engine.ui.e.h.d.e eVar2 = bVar.A;
        eVar2.getClass();
        i iVar = bVar.D;
        iVar.getClass();
        ac acVar = bVar.Q;
        acVar.getClass();
        j jVar2 = bVar.W;
        jVar2.getClass();
        h hVar6 = bVar.s;
        hVar6.getClass();
        com.google.android.apps.gsa.nga.engine.ui.e.h.y yVar2 = bVar.Z;
        yVar2.getClass();
        com.google.android.apps.gsa.nga.engine.ui.e.c.a.e eVar3 = bVar.t;
        eVar3.getClass();
        s sVar = bVar.M;
        sVar.getClass();
        com.google.android.apps.gsa.nga.engine.ui.e.h.t tVar2 = bVar.N;
        tVar2.getClass();
        com.google.android.apps.gsa.nga.engine.ui.e.c.b bVar3 = bVar.u;
        bVar3.getClass();
        com.google.android.apps.gsa.nga.engine.ui.e.h.y yVar3 = bVar.O;
        yVar3.getClass();
        com.google.android.apps.gsa.nga.engine.ui.e.h.e.s sVar2 = bVar.w;
        sVar2.getClass();
        Set set2 = bVar.y;
        set2.getClass();
        com.google.android.apps.gsa.nga.shared.ak.e eVar4 = bVar.C;
        eVar4.getClass();
        com.google.android.apps.gsa.nga.engine.ui.d.e.h hVar7 = bVar.V;
        hVar7.getClass();
        return new b(ciVar, fVar, hVar, hVar2, hVar3, hVar4, context, context2, hVar5, aVar2, yVar, aVar3, agVar, cVar, apVar, tVar, bVar2, xVar, lVar, aVar4, gVar, wVar, set, fVar2, eVar, cVar2, agVar2, jVar, eVar2, iVar, bVar.L, acVar, bVar.x, jVar2, bVar.U, bVar.r, hVar6, yVar2, eVar3, sVar, tVar2, bVar3, bVar.v, yVar3, sVar2, aVar, set2, bVar.B, eVar4, hVar7);
    }

    public final /* bridge */ /* synthetic */ Object a() {
        throw null;
    }
}
