package com.google.android.apps.gsa.nga.engine.ui.e.h.a;

import android.content.Context;
import com.google.android.apps.gsa.nga.engine.ae.ad;
import com.google.android.apps.gsa.nga.engine.ak.s.m;
import com.google.android.apps.gsa.nga.engine.am.g;
import com.google.android.apps.gsa.nga.engine.education.w;
import com.google.android.apps.gsa.nga.engine.n.e.ac;
import com.google.android.apps.gsa.nga.engine.ui.d.e.h;
import com.google.android.apps.gsa.nga.engine.ui.e.f.a.u;
import com.google.android.apps.gsa.nga.engine.ui.e.h.d.e;
import com.google.android.apps.gsa.nga.engine.ui.e.h.s;
import com.google.android.apps.gsa.nga.engine.v.a.j;
import com.google.android.apps.gsa.nga.shared.aj.a.c;
import com.google.android.apps.gsa.nga.shared.f.a.ag;
import com.google.android.apps.gsa.nga.shared.f.a.ap;
import com.google.android.apps.gsa.nga.shared.f.a.t;
import com.google.android.apps.gsa.nga.shared.q.a.x;
import com.google.android.apps.gsa.nga.shared.ui.assistlayer.e.l;
import com.google.android.apps.search.assistant.surfaces.voice.m.b.a.c.i;
import com.google.android.libraries.search.account.y;
import com.google.common.base.ci;
import com.google.common.v.f;
import java.util.Set;

/* loaded from: classes-dex2jar.jar:com/google/android/apps/gsa/nga/engine/ui/e/h/a/b.class */
public final class b {
    public final e A;
    public final Set B;
    public final com.google.android.apps.gsa.nga.shared.ak.e C;
    public final i D;
    public final y E;
    public final ag F;
    public final c G;
    public final t H;
    public final x I;
    public final com.google.android.apps.gsa.nga.engine.aa.c J;
    public final com.google.android.apps.gsa.nga.engine.ac.a.ag K;
    public final com.google.android.apps.gsa.nga.engine.ui.f.a.a L;
    public final s M;
    public final com.google.android.apps.gsa.nga.engine.ui.e.h.t N;
    public final com.google.android.apps.gsa.nga.engine.ui.e.h.y O;
    public final ad P;
    public final ac Q;
    public final com.google.android.apps.gsa.nga.engine.ak.v.a.e R;
    public final com.google.android.apps.gsa.nga.engine.c.d.a.b S;
    public final j T;
    public final u U;
    public final h V;
    public final j W;
    public final com.google.android.apps.gsa.shared.o.b.a.a X;
    public final ap Y;
    public final com.google.android.apps.gsa.nga.engine.ui.e.h.y Z;

    /* renamed from: a, reason: collision with root package name */
    public final ci f740a;
    public final f b;
    public final com.google.android.libraries.gsa.h.h c;
    public final com.google.android.libraries.gsa.h.h d;
    public final com.google.android.libraries.gsa.h.h e;
    public final com.google.android.libraries.gsa.h.h f;
    public final Context g;
    public final Context h;
    public final com.google.android.apps.gsa.shared.logger.b.h i;
    public final com.google.android.apps.gsa.shared.util.q.a j;
    public final com.google.android.apps.gsa.shared.o.a.a k;
    public final com.google.android.apps.gsa.nga.shared.p.b l;
    public final l m;
    public final com.google.android.apps.gsa.nga.engine.am.a.a n;
    public final g o;
    public final w p;
    public final Set q;
    public final com.google.android.apps.gsa.nga.shared.ui.a.a r;
    public final com.google.android.libraries.gsa.h.h s;
    public final com.google.android.apps.gsa.nga.engine.ui.e.c.a.e t;
    public final com.google.android.apps.gsa.nga.engine.ui.e.c.b u;
    public final com.google.cj.g.b v;
    public final com.google.android.apps.gsa.nga.engine.ui.e.h.e.s w;
    public final m x;
    public final Set y;
    public final com.google.android.apps.gsa.nga.engine.am.f z;

    public b(ci ciVar, f fVar, com.google.android.libraries.gsa.h.h hVar, com.google.android.libraries.gsa.h.h hVar2, com.google.android.libraries.gsa.h.h hVar3, com.google.android.libraries.gsa.h.h hVar4, Context context, Context context2, com.google.android.apps.gsa.shared.logger.b.h hVar5, com.google.android.apps.gsa.shared.util.q.a aVar, y yVar, com.google.android.apps.gsa.shared.o.b.a.a aVar2, com.google.android.apps.gsa.shared.o.a.a aVar3, ag agVar, c cVar, ap apVar, t tVar, com.google.android.apps.gsa.nga.shared.p.b bVar, x xVar, l lVar, com.google.android.apps.gsa.nga.engine.am.a.a aVar4, g gVar, w wVar, Set set, com.google.android.apps.gsa.nga.engine.am.f fVar2, com.google.android.apps.gsa.nga.engine.ak.v.a.e eVar, com.google.android.apps.gsa.nga.engine.aa.c cVar2, com.google.android.apps.gsa.nga.engine.ac.a.ag agVar2, com.google.android.apps.gsa.nga.engine.c.d.a.b bVar2, j jVar, e eVar2, i iVar, com.google.android.apps.gsa.nga.engine.ui.f.a.a aVar5, ac acVar, m mVar, j jVar2, u uVar, com.google.android.apps.gsa.nga.shared.ui.a.a aVar6, com.google.android.libraries.gsa.h.h hVar6, com.google.android.apps.gsa.nga.engine.ui.e.h.y yVar2, com.google.android.apps.gsa.nga.engine.ui.e.c.a.e eVar3, s sVar, com.google.android.apps.gsa.nga.engine.ui.e.h.t tVar2, com.google.android.apps.gsa.nga.engine.ui.e.c.b bVar3, com.google.cj.g.b bVar4, com.google.android.apps.gsa.nga.engine.ui.e.h.y yVar3, com.google.android.apps.gsa.nga.engine.ui.e.h.e.s sVar2, ad adVar, Set set2, Set set3, com.google.android.apps.gsa.nga.shared.ak.e eVar4, h hVar7) {
        this.f740a = ciVar;
        this.b = fVar;
        this.d = hVar2;
        this.c = hVar;
        this.e = hVar3;
        this.f = hVar4;
        this.g = context;
        this.h = context2;
        this.i = hVar5;
        this.j = aVar;
        this.E = yVar;
        this.X = aVar2;
        this.k = aVar3;
        this.F = agVar;
        this.G = cVar;
        this.Y = apVar;
        this.H = tVar;
        this.l = bVar;
        this.I = xVar;
        this.m = lVar;
        this.n = aVar4;
        this.o = gVar;
        this.p = wVar;
        this.q = set;
        this.z = fVar2;
        this.R = eVar;
        this.J = cVar2;
        this.K = agVar2;
        this.S = bVar2;
        this.T = jVar;
        this.A = eVar2;
        this.D = iVar;
        this.L = aVar5;
        this.Q = acVar;
        this.x = mVar;
        this.W = jVar2;
        this.r = aVar6;
        this.s = hVar6;
        this.Z = yVar2;
        this.t = eVar3;
        this.M = sVar;
        this.N = tVar2;
        this.u = bVar3;
        this.v = bVar4;
        this.O = yVar3;
        this.w = sVar2;
        this.P = adVar;
        this.y = set2;
        this.B = set3;
        this.C = eVar4;
        this.U = uVar;
        this.V = hVar7;
    }
}
