package com.google.android.apps.gsa.nga.engine.ui.e.d;

import android.content.Context;
import com.google.android.apps.gsa.nga.engine.ak.s.m;
import com.google.android.apps.gsa.nga.engine.ak.v.a.e;
import com.google.android.apps.gsa.nga.engine.am.g;
import com.google.android.apps.gsa.nga.engine.education.w;
import com.google.android.apps.gsa.nga.engine.n.e.ac;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.aj;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.p;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.af;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.bc;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.bf;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.bp;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.bs;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.bz;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.ck;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.co;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.ct;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.k;
import com.google.android.apps.gsa.nga.engine.ui.e.e.a.n;
import com.google.android.apps.gsa.nga.engine.ui.e.f.a.u;
import com.google.android.apps.gsa.nga.engine.ui.e.h.s;
import com.google.android.apps.gsa.nga.engine.ui.e.r.a.q;
import com.google.android.apps.gsa.nga.engine.v.a.j;
import com.google.android.apps.gsa.nga.shared.aj.a.c;
import com.google.android.apps.gsa.nga.shared.f.a.ag;
import com.google.android.apps.gsa.nga.shared.f.a.ap;
import com.google.android.apps.gsa.nga.shared.f.a.t;
import com.google.android.apps.gsa.nga.shared.q.a.x;
import com.google.android.apps.gsa.nga.shared.ui.assistlayer.e.l;
import com.google.android.apps.search.assistant.surfaces.voice.m.b.a.c.i;
import com.google.android.libraries.search.account.y;
import com.google.common.base.ci;
import com.google.common.v.f;
import e.c.d;
import e.c.h;
import java.util.LinkedHashMap;
import java.util.Set;

/* loaded from: classes-dex2jar.jar:com/google/android/apps/gsa/nga/engine/ui/e/d/b.class */
public final class b {
    private final h A;
    private final h B;
    private final h C;
    private final h D;
    private final h E;
    private final h F;
    private final h G;
    private final h H;
    private final h I;
    private final h J;
    private final h K;
    private final h L;
    private final h M;
    private final h N;
    private final h O;
    private final h P;
    private final h Q;
    private final h R;
    private final h S;
    private final h T;
    private final h U;
    private final h V;
    private final h W;
    private final h X;
    private final h Y;
    private final h Z;

    /* renamed from: a, reason: collision with root package name */
    public final h f704a;
    private final h aA;
    private final h aB;
    private final h aC;
    private final h aD;
    private final h aE;
    private final h aF;
    private final h aG;
    private final h aH;
    private final h aI;
    private final h aJ;
    private final h aK;
    private final h aL;
    private final h aM;
    private final h aN;
    private final h aO;
    private final h aP;
    private final h aQ;
    private final h aR;
    private final h aS;
    private final h aT;
    private final h aU;
    private final h aV;
    private final h aW;
    private final h aX;
    private final h aY;
    private final h aZ;
    private final h aa;
    private final h ab;
    private final h ac;
    private final h ad;
    private final h ae;
    private final h af;
    private final h ag;
    private final h ah;
    private final h ai;
    private final h aj;
    private final h ak;
    private final h al;
    private final h am;
    private final h an;
    private final h ao;
    private final h ap;
    private final h aq;
    private final h ar;
    private final h as;
    private final h at;
    private final h au;
    private final h av;
    private final h aw;
    private final h ax;
    private final h ay;
    private final h az;
    public final h b;
    private final h ba;
    private final h bb;
    private final h bc;
    private final h bd;
    private final h be;
    private final h bf;
    private final h bg;
    private final h bh;
    private final h bi;
    private final h bj;
    private final h bk;
    private final h bl;
    private final h bm;
    private final h bn;
    public final h c;
    public final h d;
    public final h e;
    public final h f;
    public final h g;
    public final h h;
    public final h i;
    public final h j;
    public final h k;
    private final h l;
    private final h m;
    private final h n;
    private final h o;
    private final h p;
    private final h q;
    private final h r;
    private final h s;
    private final h t;
    private final h u;
    private final h v;
    private final h w;
    private final h x;
    private final h y;
    private final h z;

    public b(ci ciVar, f fVar, com.google.android.libraries.gsa.h.h hVar, com.google.android.libraries.gsa.h.h hVar2, com.google.android.libraries.gsa.h.h hVar3, com.google.android.libraries.gsa.h.h hVar4, Context context, Context context2, com.google.android.apps.gsa.shared.logger.b.h hVar5, com.google.android.apps.gsa.shared.util.q.a aVar, y yVar, com.google.android.apps.gsa.shared.o.a.a aVar2, ag agVar, c cVar, ap apVar, t tVar, com.google.android.apps.gsa.nga.shared.p.b bVar, x xVar, l lVar, com.google.android.apps.gsa.nga.engine.am.a.a aVar3, g gVar, w wVar, Set set, com.google.android.apps.gsa.nga.engine.am.f fVar2, e eVar, com.google.android.apps.gsa.nga.engine.aa.c cVar2, com.google.android.apps.gsa.nga.engine.ac.a.ag agVar2, j jVar, com.google.android.apps.gsa.nga.engine.ui.e.h.d.e eVar2, i iVar, com.google.android.apps.gsa.nga.engine.ui.f.a.a aVar4, ac acVar, m mVar, j jVar2, u uVar, com.google.android.apps.gsa.nga.shared.ui.a.a aVar5, com.google.android.libraries.gsa.h.h hVar6, com.google.android.apps.gsa.nga.engine.ui.e.h.y yVar2, com.google.android.apps.gsa.nga.engine.ui.e.c.a.e eVar3, s sVar, com.google.android.apps.gsa.nga.engine.ui.e.h.t tVar2, com.google.android.apps.gsa.nga.engine.ui.e.c.b bVar2, com.google.cj.g.b bVar3, com.google.android.apps.gsa.nga.engine.ui.e.h.y yVar3, com.google.android.apps.gsa.nga.engine.ui.e.h.e.s sVar2, com.google.android.apps.gsa.nga.engine.ui.e.h.a.a aVar6, Set set2, Set set3, com.google.android.apps.gsa.nga.shared.ak.e eVar4, com.google.android.apps.gsa.nga.engine.ui.d.e.h hVar7) {
        d b = e.c.e.b(hVar5);
        this.l = b;
        d b2 = e.c.e.b(yVar2);
        this.m = b2;
        d b3 = e.c.e.b(hVar2);
        this.n = b3;
        d b4 = e.c.e.b(context2);
        this.o = b4;
        d b5 = e.c.e.b(yVar);
        this.p = b5;
        h c = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.r.a.m(b3, b4, b5, 0));
        this.q = c;
        h c2 = e.c.c.c(new q(b, b2, c, b3));
        this.r = c2;
        d b6 = e.c.e.b(acVar);
        this.s = b6;
        d b7 = e.c.e.b(hVar4);
        this.t = b7;
        d b8 = e.c.e.b(hVar);
        this.u = b8;
        d b9 = e.c.e.b(hVar6);
        this.v = b9;
        d b10 = e.c.e.b(context);
        this.w = b10;
        e.c.b bVar4 = new e.c.b();
        this.x = bVar4;
        d b11 = e.c.e.b(eVar);
        this.y = b11;
        d b12 = e.c.e.b(hVar7);
        this.z = b12;
        d b13 = e.c.e.b(aVar);
        this.A = b13;
        h c3 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.b.a.s(b10, bVar4, b9, b11, b12, b13, 0));
        this.f704a = c3;
        com.google.android.apps.gsa.nga.engine.ui.e.b.b.a aVar7 = new com.google.android.apps.gsa.nga.engine.ui.e.b.b.a(c3, 1);
        this.B = aVar7;
        d b14 = e.c.e.b(eVar3);
        this.C = b14;
        a aVar8 = new a(b14, 1);
        this.D = aVar8;
        d b15 = e.c.e.b(eVar4);
        this.E = b15;
        com.google.android.apps.gsa.nga.engine.ui.e.b.b.a aVar9 = new com.google.android.apps.gsa.nga.engine.ui.e.b.b.a(c3, 0);
        this.F = aVar9;
        d b16 = e.c.e.b(aVar6);
        this.G = b16;
        h c4 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.l.a.d(b9, b15, aVar9, b16, c2));
        this.H = c4;
        com.google.android.apps.gsa.nga.engine.ui.e.l.b.a aVar10 = new com.google.android.apps.gsa.nga.engine.ui.e.l.b.a(c4);
        this.I = aVar10;
        h c5 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.k.a.f(b9, b14, c2, b13));
        this.b = c5;
        h c6 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.n.a.j(b9, aVar7, aVar8, aVar10, c5));
        this.c = c6;
        e.c.b.b(bVar4, new com.google.android.apps.gsa.nga.engine.ui.e.n.b.b(c6));
        d b17 = e.c.e.b(bVar2);
        this.J = b17;
        d b18 = e.c.e.b(mVar);
        this.K = b18;
        d b19 = e.c.e.b(tVar);
        this.L = b19;
        d b20 = e.c.e.b(uVar);
        this.M = b20;
        d b21 = e.c.e.b(aVar2);
        this.N = b21;
        d b22 = e.c.e.b(ciVar);
        this.O = b22;
        h c7 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.j.a.b(b9));
        this.P = c7;
        com.google.android.apps.gsa.nga.engine.ui.e.j.b.a aVar11 = new com.google.android.apps.gsa.nga.engine.ui.e.j.b.a(c7, 0);
        this.Q = aVar11;
        h c8 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.f.a.s(c2, b6, b7, b8, b9, bVar4, b17, b18, b15, b19, b13, b, b5, b20, aVar7, b21, b22, aVar11, b10));
        this.R = c8;
        h c9 = e.c.c.c(new k(b9, bVar4));
        this.d = c9;
        d b23 = e.c.e.b(yVar3);
        this.S = b23;
        d b24 = e.c.e.b(gVar);
        this.T = b24;
        h c10 = e.c.c.c(new aj(b9, bVar4, 2));
        this.e = c10;
        d b25 = e.c.e.b(lVar);
        this.U = b25;
        h c11 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.y(b24, bVar4, c10, b25));
        this.V = c11;
        d b26 = e.c.e.b(sVar2);
        this.W = b26;
        com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.aj ajVar = new com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.aj(c6, c11, b26, b9);
        this.X = ajVar;
        d b27 = e.c.e.b(bVar);
        this.Y = b27;
        d b28 = e.c.e.b(tVar2);
        this.Z = b28;
        a aVar12 = new a(b28, 0);
        this.aa = aVar12;
        d b29 = e.c.e.b(sVar);
        this.ab = b29;
        h c12 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.e.a.i(b27, aVar12, b17, b29));
        this.ac = c12;
        h c13 = e.c.c.c(new aj(b27, aVar12, 0));
        this.ad = c13;
        h c14 = e.c.c.c(new n(b27, aVar8, aVar12, b17, c12, c13));
        this.ae = c14;
        d b30 = e.c.e.b(set);
        this.af = b30;
        d b31 = e.c.e.b(xVar);
        this.ag = b31;
        d b32 = e.c.e.b(fVar);
        this.ah = b32;
        com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.t tVar3 = new com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.t(b13);
        this.ai = tVar3;
        h c15 = e.c.c.c(new p(c11, b30, b3, b9, b13, aVar12, b31, b32, b19, tVar3));
        this.aj = c15;
        d b33 = e.c.e.b(cVar2);
        this.ak = b33;
        h c16 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.ac(b33, b3, b17));
        this.al = c16;
        h c17 = e.c.c.c(new aj(b17, c13, 1, null));
        this.am = c17;
        d b34 = e.c.e.b(wVar);
        this.an = b34;
        d b35 = e.c.e.b(agVar);
        this.ao = b35;
        d b36 = e.c.e.b(iVar);
        this.ap = b36;
        com.google.android.apps.gsa.nga.shared.aa.a aVar13 = new com.google.android.apps.gsa.nga.shared.aa.a(b15);
        this.aq = aVar13;
        com.google.android.apps.gsa.nga.engine.ui.e.e.a.b.h hVar8 = new com.google.android.apps.gsa.nga.engine.ui.e.e.a.b.h(b3, b34, b35, b13, b27, b36, aVar13, b32);
        this.ar = hVar8;
        h c18 = e.c.c.c(com.google.android.apps.gsa.nga.engine.ui.e.q.b.a.f792a);
        this.as = c18;
        ct ctVar = new ct(aVar7, c18, b32, b9);
        this.at = ctVar;
        e.c.b bVar5 = new e.c.b();
        this.au = bVar5;
        d b37 = e.c.e.b(fVar2);
        this.av = b37;
        bf bfVar = new bf(c18, ctVar, aVar7, b9, bVar5, b37);
        this.aw = bfVar;
        bp bpVar = new bp(b9, b17, ajVar, bVar4, aVar10, aVar7, aVar8, aVar12, b27);
        this.ax = bpVar;
        com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.d dVar = new com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.d(b10);
        this.ay = dVar;
        com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.b bVar6 = new com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.b(dVar);
        this.az = bVar6;
        e.c.b.b(bVar5, new ck(b, c14, c15, c16, c17, hVar8, aVar12, aVar8, aVar7, c18, bfVar, bpVar, b9, b3, b13, bVar6, b26, bVar4));
        d b38 = e.c.e.b(apVar);
        this.aA = b38;
        d b39 = e.c.e.b(cVar);
        this.aB = b39;
        h c19 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.e.a.g(b27, b17, aVar8, aVar7, b9, b38, b13, b39, aVar12));
        this.aC = c19;
        d b40 = e.c.e.b(eVar2);
        this.aD = b40;
        com.google.android.apps.gsa.nga.engine.ui.e.e.c.a.b bVar7 = new com.google.android.apps.gsa.nga.engine.ui.e.e.c.a.b(bVar6, b27, aVar12);
        this.aE = bVar7;
        com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.e eVar5 = new com.google.android.apps.gsa.nga.engine.ui.e.e.a.c.e(bVar7, b40, b17, ajVar, b9, c6, bVar4);
        this.aF = eVar5;
        bz bzVar = new bz(c19, ajVar, bVar4, c6, b9);
        this.aG = bzVar;
        h c20 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.a.a.g(c2, b9, aVar8));
        this.f = c20;
        d b41 = e.c.e.b(jVar);
        this.aH = b41;
        af afVar = new af(c15, c19, b40, eVar5, ajVar, bzVar, aVar7, aVar8, c18, b32, b9, b3, c20, b13, b17, bVar6, b41, c6, b);
        this.aI = afVar;
        co coVar = new co(b9, bVar4, b27, aVar12, bVar6, b13);
        this.aJ = coVar;
        bs bsVar = new bs(b9, bVar4, b27, aVar12, bVar6);
        this.aK = bsVar;
        com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.af afVar2 = new com.google.android.apps.gsa.nga.engine.ui.e.e.a.a.af(b19);
        this.aL = afVar2;
        d b42 = e.c.e.b(set3);
        this.aM = b42;
        h c21 = e.c.c.c(new bc(ajVar, bVar5, afVar, ctVar, aVar8, bVar4, bpVar, c14, b25, c2, coVar, bsVar, afVar2, b42, b13, b36, b3));
        this.aN = c21;
        com.google.android.apps.gsa.nga.engine.ui.e.e.b.c cVar3 = new com.google.android.apps.gsa.nga.engine.ui.e.e.b.c(c21);
        this.aO = cVar3;
        com.google.android.apps.gsa.nga.engine.ui.e.j.b.a aVar14 = new com.google.android.apps.gsa.nga.engine.ui.e.j.b.a(c7, 1);
        this.aP = aVar14;
        com.google.android.apps.gsa.nga.engine.ui.e.b.a.e eVar6 = new com.google.android.apps.gsa.nga.engine.ui.e.b.a.e(bVar4, aVar8, c3, b17, aVar14, aVar11);
        this.aQ = eVar6;
        h c22 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.b.a.s(c2, b17, eVar6, b27, aVar12, cVar3, 1, null));
        this.aR = c22;
        d b43 = e.c.e.b(set2);
        this.aS = b43;
        h c23 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.g(cVar3, bVar4, b17, c22, aVar14, aVar11, b9, b43, b11));
        this.g = c23;
        d b44 = e.c.e.b(hVar3);
        this.aT = b44;
        d b45 = e.c.e.b(agVar2);
        this.aU = b45;
        h c24 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.n.a.b(bVar4, b44, b45));
        this.aV = c24;
        h c25 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.b.a.i(c2, c3));
        this.aW = c25;
        h c26 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.o.a.f(b9, bVar4, aVar7, c2, b32));
        this.aX = c26;
        d b46 = e.c.e.b(bVar3);
        this.aY = b46;
        d b47 = e.c.e.b(aVar3);
        this.aZ = b47;
        com.google.android.apps.gsa.nga.engine.ui.e.p.b.b bVar8 = new com.google.android.apps.gsa.nga.engine.ui.e.p.b.b(b10);
        this.ba = bVar8;
        h c27 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.p.a.c(bVar8, aVar7, aVar8, b43, c6, c6, b10, b13));
        this.bb = c27;
        com.google.android.apps.gsa.nga.engine.ui.e.t.b.b bVar9 = new com.google.android.apps.gsa.nga.engine.ui.e.t.b.b(b10);
        this.bc = bVar9;
        h c28 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.t.a.g(b17, aVar8, aVar10, b9, c2, bVar9, aVar12, bVar4));
        this.bd = c28;
        h c29 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.i.a.e(b46, b9, b8, b47, c7, c19, c27, c5, c28, c8));
        this.be = c29;
        h c30 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.q.a.e(b9, c18, aVar8));
        this.h = c30;
        h c31 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.r.a.m(aVar8, aVar12, c2, 1, null));
        this.bf = c31;
        h c32 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.r.a.h(aVar8, bVar4, aVar11, aVar10, b17, c3, c2, c20));
        this.bg = c32;
        h c33 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.r.a.j(c2));
        this.bh = c33;
        com.google.android.apps.gsa.nga.engine.ui.e.m.a.d dVar2 = new com.google.android.apps.gsa.nga.engine.ui.e.m.a.d(c2, b13, bVar4, b17, aVar7);
        this.bi = dVar2;
        d b48 = e.c.e.b(jVar2);
        this.bj = b48;
        h c34 = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.g.a.e(c2, bVar4, aVar7, b48));
        this.bk = c34;
        h hVar9 = e.c.g.b;
        LinkedHashMap d = e.c.k.d(25);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar10 = com.google.android.apps.gsa.nga.engine.ui.e.h.NGA_TO_OPA_CARD_STATE;
        hVar10.getClass();
        d.put(hVar10, c23);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar11 = com.google.android.apps.gsa.nga.engine.ui.e.h.TTS_STATUS;
        hVar11.getClass();
        d.put(hVar11, c20);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar12 = com.google.android.apps.gsa.nga.engine.ui.e.h.SCREENSHOT_STATE_OBSERVER;
        hVar12.getClass();
        d.put(hVar12, c5);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar13 = com.google.android.apps.gsa.nga.engine.ui.e.h.UI_SESSION;
        hVar13.getClass();
        d.put(hVar13, c6);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar14 = com.google.android.apps.gsa.nga.engine.ui.e.h.INTERACTION_CONTROLLER;
        hVar14.getClass();
        d.put(hVar14, c24);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar15 = com.google.android.apps.gsa.nga.engine.ui.e.h.ICONS;
        hVar15.getClass();
        d.put(hVar15, c22);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar16 = com.google.android.apps.gsa.nga.engine.ui.e.h.CARD;
        hVar16.getClass();
        d.put(hVar16, c25);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar17 = com.google.android.apps.gsa.nga.engine.ui.e.h.CARD_VISIBILITY_OBSERVER;
        hVar17.getClass();
        d.put(hVar17, c3);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar18 = com.google.android.apps.gsa.nga.engine.ui.e.h.NAVBAR_VISIBILITY;
        hVar18.getClass();
        d.put(hVar18, c26);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar19 = com.google.android.apps.gsa.nga.engine.ui.e.h.TACTILE_GREETING;
        hVar19.getClass();
        d.put(hVar19, c14);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar20 = com.google.android.apps.gsa.nga.engine.ui.e.h.INPUT_PLATE;
        hVar20.getClass();
        d.put(hVar20, c21);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar21 = com.google.android.apps.gsa.nga.engine.ui.e.h.SUGGESTIONS_BUFFER;
        hVar21.getClass();
        d.put(hVar21, c10);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar22 = com.google.android.apps.gsa.nga.engine.ui.e.h.FRE_SUGGESTIONS;
        hVar22.getClass();
        d.put(hVar22, c9);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar23 = com.google.android.apps.gsa.nga.engine.ui.e.h.CHIPS_V2;
        hVar23.getClass();
        d.put(hVar23, c11);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar24 = com.google.android.apps.gsa.nga.engine.ui.e.h.LEGAL_NOTICE;
        hVar24.getClass();
        d.put(hVar24, c19);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar25 = com.google.android.apps.gsa.nga.engine.ui.e.h.ASSIST_UI_OUTPUT_ACTIONS_RECEIVER;
        hVar25.getClass();
        d.put(hVar25, c29);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar26 = com.google.android.apps.gsa.nga.engine.ui.e.h.TRANSCRIPTION;
        hVar26.getClass();
        d.put(hVar26, c30);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar27 = com.google.android.apps.gsa.nga.engine.ui.e.h.CONFIGURATION;
        hVar27.getClass();
        d.put(hVar27, c31);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar28 = com.google.android.apps.gsa.nga.engine.ui.e.h.EDGES_LIGHTS;
        hVar28.getClass();
        d.put(hVar28, c32);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar29 = com.google.android.apps.gsa.nga.engine.ui.e.h.SHELF;
        hVar29.getClass();
        d.put(hVar29, c33);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar30 = com.google.android.apps.gsa.nga.engine.ui.e.h.WARM_ACTIONS_STATE;
        hVar30.getClass();
        d.put(hVar30, c28);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar31 = com.google.android.apps.gsa.nga.engine.ui.e.h.SCREEN_STATE;
        hVar31.getClass();
        d.put(hVar31, c4);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar32 = com.google.android.apps.gsa.nga.engine.ui.e.h.AMBIENT_VISUAL_SEARCH;
        hVar32.getClass();
        d.put(hVar32, c8);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar33 = com.google.android.apps.gsa.nga.engine.ui.e.h.SECONDARY_DISPLAY;
        hVar33.getClass();
        d.put(hVar33, dVar2);
        com.google.android.apps.gsa.nga.engine.ui.e.h hVar34 = com.google.android.apps.gsa.nga.engine.ui.e.h.LOGGING;
        hVar34.getClass();
        d.put(hVar34, c34);
        e.c.g gVar2 = new e.c.g(d);
        this.bl = gVar2;
        this.i = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.m(b9, b23, gVar2));
        d b49 = e.c.e.b(aVar4);
        this.bm = b49;
        d b50 = e.c.e.b(aVar5);
        this.bn = b50;
        this.j = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.s.a.f(bVar4, aVar7, aVar8, b9, b23, b49, b50));
        this.k = e.c.c.c(new com.google.android.apps.gsa.nga.engine.ui.e.a.a.c(b22, b9, bVar4, c2));
    }

    public final com.google.android.apps.gsa.nga.engine.ui.e.l.a.c a() {
        return (com.google.android.apps.gsa.nga.engine.ui.e.l.a.c) this.H.a();
    }
}
