package com.google.android.apps.gsa.nga.engine.education.a;

import com.google.common.b.fd;
import com.google.common.b.fq;
import com.google.common.b.fu;
import com.google.common.b.ha;
import java.util.EnumSet;

/* loaded from: classes-dex2jar.jar:com/google/android/apps/gsa/nga/engine/education/a/p.class */
public final class p {

    /* renamed from: a */
    public static final ha f555a = fd.b(EnumSet.of(t.HOME_SCREEN, t.TIMEOUT_HOMESCREEN));
    public static final ha b = fd.b(EnumSet.of(t.IN_APP, new t[0]));
    public static final ha c = fd.b(EnumSet.of(t.HANDS_FREE, new t[0]));
    public static final fu d = fu.p(com.google.g.x.a.w.b, t.HOME_SCREEN, com.google.g.x.a.w.c, t.IN_APP, com.google.g.x.a.w.d, t.TIMEOUT_HOMESCREEN, com.google.g.x.a.w.e, t.TIMEOUT_IN_APP);
    public static final fu e;
    public static final fu f;
    public static final fu g;
    public static final fu h;

    static {
        ha.w("com.google.android.apps.messaging", "com.google.android.dialer", "com.google.android.calendar", "com.google.android.GoogleCamera", "com.android.chrome", "com.facebook.katana", new String[]{"com.google.android.apps.maps", "com.google.android.apps.photos", "com.instagram.android", "com.google.android.apps.nexuslauncher", "com.google.android.youtube"});
        fq fqVar = new fq(4);
        fqVar.i("com.amazon.mShop.android.shopping", 2132093125);
        fqVar.i("com.google.android.calendar", 2132093188);
        fqVar.i("com.google.android.apps.tachyon", 2132093130);
        fqVar.i("com.facebook.katana", 2132093185);
        fqVar.i("com.imdb.mobile", 2132093138);
        fqVar.i("com.instagram.android", 2132093139);
        fqVar.i("com.android.vending", 2132093136);
        fqVar.i("com.yelp.android", 2132093133);
        fqVar.i("com.americanexpress.android.acctsvcs.us", 2132093178);
        fqVar.i("com.google.android.apps.chromecast.app", 2132093166);
        fqVar.i("com.ebay.mobile", 2132093131);
        fqVar.i("com.nest.android", 2132093171);
        fqVar.i("com.nike.plusgps", 2132093149);
        fqVar.i("com.pinterest", 2132093152);
        fqVar.i("com.runtastic.android", 2132093124);
        fqVar.i("com.twitter.android", 2132093163);
        fqVar.i("com.walmart.android", 2132093164);
        fqVar.i("com.waze", 2132093177);
        fqVar.i("org.wikipedia", 2132093140);
        e = fqVar.h(false);
        fq fqVar2 = new fq(4);
        fqVar2.i("BookARide", 2132093127);
        fqVar2.i("CheckAccountBalances", 2132093143);
        fqVar2.i("CheckFlights", 2132093167);
        fqVar2.i("CheckNews", 2132093168);
        fqVar2.i("CheckNotifications", 2132093128);
        fqVar2.i("CheckWeather", 2132093169);
        fqVar2.i("ControlAppliancesAndFixtures", 2132093129);
        fqVar2.i("ControlEntertainmentSystems", 2132093172);
        fqVar2.i("ControlPhoneSettings", 2132093187);
        fqVar2.i("ControlTemperatureAndAir", 2132093129);
        fqVar2.i("ConvertUnits", 2132093173);
        fqVar2.i("FindBeautyServices", 2132093133);
        fqVar2.i("FindCalm", 2132093134);
        fqVar2.i("FindFoodAndDrink", 2132093133);
        fqVar2.i("FindFoodRecipes", 2132093175);
        fqVar2.i("FindServices", 2132093176);
        fqVar2.i("FindStores", 2132093135);
        fqVar2.i("GetAStory", 2132093180);
        fqVar2.i("GetDirections", 2132093177);
        fqVar2.i("GetInfoAboutHistoryAndEvents", 2132093137);
        fqVar2.i("GetInfoAboutMediaAndEntertainment", 2132093148);
        fqVar2.i("GetInfoAboutPeople", 2132093151);
        fqVar2.i("GetNutritionFacts", 2132093179);
        fqVar2.i("GetTranslation", 2132093181);
        fqVar2.i("MakePhoneCalls", 2132093183);
        fqVar2.i("MakeVideoCalls", 2132093142);
        fqVar2.i("ManageCalendars", 2132093182);
        fqVar2.i("ManageEmails", 2132093184);
        fqVar2.i("ManageLists", 2132093147);
        fqVar2.i("ManageMessages", 2132093144);
        fqVar2.i("ManagePaymentsAndTransfers", 2132093145);
        fqVar2.i("ManagePersonalInfo", 2132093146);
        fqVar2.i("ManagePhotos", 2132093186);
        fqVar2.i("ManageReminders", 2132093188);
        fqVar2.i("OrderFood", 2132093150);
        fqVar2.i("OtherFood", 2132093159);
        fqVar2.i("OtherEducationAndReference", 2132093141);
        fqVar2.i("OtherKidsAndFamily", 2132093132);
        fqVar2.i("OtherShopping", 2132093158);
        fqVar2.i("OtherSports", 2132093160);
        fqVar2.i("OtherTravelAndTransportation", 2132093199);
        fqVar2.i("PlayAudiobook", 2132093153);
        fqVar2.i("PlayGames", 2132093189);
        fqVar2.i("PlayMusic", 2132093190);
        fqVar2.i("PlayPodcasts", 2132093191);
        fqVar2.i("PlayRadio", 2132093192);
        fqVar2.i("PlayTvShows", 2132093193);
        fqVar2.i("PlayVideos", 2132093194);
        fqVar2.i("RememberImportantInfo", 2132093154);
        fqVar2.i("SetAlarms", 2132093155);
        fqVar2.i("SetTimers", 2132093196);
        fqVar2.i("ShopElectronicsAndOffice", 2132093195);
        fqVar2.i("ShopForArtsAndCrafts", 2132093126);
        fqVar2.i("ShopForBabyAndKids", 2132093156);
        fqVar2.i("ShopSportsAndOutdoors", 2132093157);
        fqVar2.i("TakePhotos", 2132093161);
        fqVar2.i("TellJokes", 2132093197);
        fqVar2.i("TrackExercise", 2132093162);
        fqVar2.i("UseCalculator", 2132093198);
        f = fqVar2.h(false);
        fq fqVar3 = new fq(4);
        fqVar3.i("com.google.android.calendar", "https://fonts.gstatic.com/s/i/productlogos/calendar_round_2020q4/v6/web-96dp/logo_calendar_round_2020q4_color_2x_web_96dp.png");
        fqVar3.i("com.android.chrome", "https://fonts.gstatic.com/s/i/productlogos/chrome/v4/web-96dp/logo_chrome_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.apps.tachyon", "https://fonts.gstatic.com/s/i/productlogos/duo_round/v5/web-96dp/logo_duo_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.gm", "https://fonts.gstatic.com/s/i/productlogos/gmail_round_2020q4/v6/web-96dp/logo_gmail_round_2020q4_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.apps.maps", "https://fonts.gstatic.com/s/i/productlogos/maps_round/v7/web-96dp/logo_maps_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.apps.photos", "https://fonts.gstatic.com/s/i/productlogos/photos_round/v13/web-96dp/logo_photos_round_color_2x_web_96dp.png");
        fqVar3.i("com.android.vending", "https://fonts.gstatic.com/s/i/productlogos/play_prism_round/v1/web-96dp/logo_play_prism_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.apps.translate", "https://fonts.gstatic.com/s/i/productlogos/translate_round/v5/web-96dp/logo_translate_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.youtube", "https://fonts.gstatic.com/s/i/productlogos/youtube_round/v7/web-96dp/logo_youtube_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.apps.books", "https://fonts.gstatic.com/s/i/productlogos/play_books_round/v7/web-96dp/logo_play_books_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.apps.chromecast.app", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar3.i("com.google.android.apps.podcasts", "https://fonts.gstatic.com/s/i/productlogos/podcasts_round/v6/web-96dp/logo_podcasts_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.apps.youtube.music", "https://fonts.gstatic.com/s/i/productlogos/youtube_music_round/v5/web-96dp/logo_youtube_music_round_color_2x_web_96dp.png");
        fqVar3.i("com.google.android.keep", "https://fonts.gstatic.com/s/i/productlogos/keep_round/v5/web-96dp/logo_keep_round_color_2x_web_96dp.png");
        fqVar3.i("org.wikipedia", "https://fonts.gstatic.com/s/i/productlogos/chrome/v4/web-96dp/logo_chrome_color_2x_web_96dp.png");
        g = fqVar3.h(false);
        fq fqVar4 = new fq(4);
        fqVar4.i("BookARide", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("CheckWeather", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/weather_round_color_48dp.png");
        fqVar4.i("ControlPhoneSettings", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("ConvertUnits", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("FindCalm", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("FindServices", "https://fonts.gstatic.com/s/i/productlogos/maps_round/v7/web-96dp/logo_maps_round_color_2x_web_96dp.png");
        fqVar4.i("FindStores", "https://fonts.gstatic.com/s/i/productlogos/maps_round/v7/web-96dp/logo_maps_round_color_2x_web_96dp.png");
        fqVar4.i("GetAStory", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("GetDirections", "https://fonts.gstatic.com/s/i/productlogos/maps_round/v7/web-96dp/logo_maps_round_color_2x_web_96dp.png");
        fqVar4.i("GetTranslation", "https://fonts.gstatic.com/s/i/productlogos/translate_round/v5/web-96dp/logo_translate_round_color_2x_web_96dp.png");
        fqVar4.i("MakePhoneCalls", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/dialer_round_color_48dp.png");
        fqVar4.i("ManageCalendars", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/myday_round_color_48dp.png");
        fqVar4.i("ManageEmails", "https://fonts.gstatic.com/s/i/productlogos/gmail_round_2020q4/v6/web-96dp/logo_gmail_round_2020q4_color_2x_web_96dp.png");
        fqVar4.i("ManageMessages", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/text_round_color_48dp.png");
        fqVar4.i("ManagePhotos", "https://fonts.gstatic.com/s/i/productlogos/photos_round/v13/web-96dp/logo_photos_round_color_2x_web_96dp.png");
        fqVar4.i("ManageReminders", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/reminder_round_color.png");
        fqVar4.i("OrderFood", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("PlayGames", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("PlayMusic", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/music_note_round_color_48dp.png");
        fqVar4.i("PlayPodcasts", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("PlayRadio", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("PlayTvShows", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("PlayVideos", "https://fonts.gstatic.com/s/i/productlogos/youtube_round/v7/web-96dp/logo_youtube_round_color_2x_web_96dp.png");
        fqVar4.i("RememberImportantInfo", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("SetAlarms", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/clock_round_color_48dp.png");
        fqVar4.i("SetTimers", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/clock_round_color_48dp.png");
        fqVar4.i("TakePhotos", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        fqVar4.i("UseCalculator", "https://www.gstatic.com/assistant/static/images/warmer_welcome/recap/search_round_color_48dp.png");
        h = fqVar4.h(false);
    }
}
